<a href="https://colab.research.google.com/github/sandana123kri/Deep_learning_Pytorch/blob/main/Pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**A Simple Neural Network with one neuron and 5 features**

In [1]:
### Create Model Class

import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()  #### to call the constructor of parent class
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    def forward(self,features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [2]:
### Create a dataset

features=torch.rand(10,5)

model= Model(features.shape[1]) ##Model(5)

#### forward pass
model(features)  ## Recommended
### Valid but not Recommended model.forward(features)

tensor([[0.2090],
        [0.2437],
        [0.3019],
        [0.3072],
        [0.3016],
        [0.2926],
        [0.3314],
        [0.2730],
        [0.2820],
        [0.2280]], grad_fn=<SigmoidBackward0>)

In [3]:
### Show model weights

model.linear.weight

Parameter containing:
tensor([[-0.2266, -0.2905, -0.1330, -0.4185, -0.4375]], requires_grad=True)

In [4]:
### Show model bias

model.linear.bias

Parameter containing:
tensor([-0.1678], requires_grad=True)

In [5]:
!pip install torchinfo

In [6]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

**Model 2: A neural network with 5 features. 1 hidden layer containing 3 neurons and 1 output layer with 1 Neuron**

Activation function:
   Hidden Layer: ReLU
   Output Layer: Sigmoid

In [7]:
class Model2(nn.Module):
    def __init__(self,num_features):
        super().__init__()  #### to call the constructor of parent class
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
    def forward(self,features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [8]:
model2=Model2(features.shape[1])
model2(features)

tensor([[0.4229],
        [0.4338],
        [0.4418],
        [0.4357],
        [0.4468],
        [0.4387],
        [0.4353],
        [0.4394],
        [0.4248],
        [0.4244]], grad_fn=<SigmoidBackward0>)

In [9]:
#### Show weights & bias of neural network

print(model2.linear1.weight)
print(model2.linear2.weight)
print(model2.linear1.bias)
print(model2.linear2.bias)

Parameter containing:
tensor([[ 0.3149,  0.4356, -0.2309,  0.3703, -0.2030],
        [ 0.3277, -0.2067,  0.0045, -0.2489, -0.0192],
        [ 0.2150, -0.0709,  0.0433,  0.3779, -0.0776]], requires_grad=True)
Parameter containing:
tensor([[-0.2080, -0.3995,  0.3507]], requires_grad=True)
Parameter containing:
tensor([ 0.3534, -0.1058, -0.2549], requires_grad=True)
Parameter containing:
tensor([-0.1283], requires_grad=True)


In [10]:
summary(model2,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

**Model 2: using nn.Sequential**

In [11]:
class Model3(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [12]:
model3=Model3(features.shape[1])
model3(features)

tensor([[0.4515],
        [0.4521],
        [0.4495],
        [0.4372],
        [0.4136],
        [0.4443],
        [0.4702],
        [0.4516],
        [0.4633],
        [0.4521]], grad_fn=<SigmoidBackward0>)

In [13]:
#### Show the weights and biases

print(model3.network[0].weight)
print(model3.network[2].weight)
print(model3.network[0].bias)
print(model3.network[2].bias)

Parameter containing:
tensor([[ 0.2167, -0.1960,  0.2129, -0.3363, -0.1991],
        [-0.3311, -0.0274, -0.3378, -0.0437, -0.4369],
        [ 0.3351, -0.2554,  0.3733,  0.0925,  0.2075]], requires_grad=True)
Parameter containing:
tensor([[-0.0596,  0.4483, -0.5750]], requires_grad=True)
Parameter containing:
tensor([ 0.3638,  0.3934, -0.3775], requires_grad=True)
Parameter containing:
tensor([-0.1923], requires_grad=True)


In [14]:
summary(model3,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model3                                   [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00