<a href="https://colab.research.google.com/github/sandana123kri/Deep_learning_Pytorch/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())


2.6.0+cu124
True


In [ ]:
if(torch.cuda.is_available()):
  device = torch.device('cuda')
else:
  device = torch.device('cpu')
print(device)
print(torch.cuda.get_device_name(0))

cuda
Tesla T4


Creating Tensors

In [ ]:
### using empty
a=torch.empty(2,3)


In [ ]:
### check type
type(a)

torch.Tensor

In [ ]:
### using zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#### using ones
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#### using rand
torch.rand(2,3)

tensor([[0.8531, 0.4316, 0.1290],
        [0.3031, 0.9975, 0.2265]])

In [ ]:
#### use of seed
torch.rand(2,3)

tensor([[0.3973, 0.2714, 0.2108],
        [0.5440, 0.5462, 0.6602]])

In [ ]:
### manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
##### using tensor
torch.tensor([[1,2,3],[5,6,7]])

tensor([[1, 2, 3],
        [5, 6, 7]])

In [ ]:
### other ways
print("using arange ---->", torch.arange(0,10))

print("using linspace ---->", torch.linspace(0,10,10))

print("using eye ------>", torch.eye(5))

print("using full ---->", torch.full((5,5), 5))

using arange ----> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace ----> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye ------> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ----> tensor([[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]])


Tensor Shapes

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[3616445622929465956, 6067529767738944821, 4121420600524290096],
        [6499315732087648302, 7309453675965983778, 8315168162784306286]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

Tensors DataType

In [ ]:
### find data type
x.dtype

torch.int64

In [ ]:
#### assign data type

torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
#### using to()

x.to(torch.float32)
x

tensor([[1, 2, 3],
        [4, 5, 6]])

Mathematical Opearations

1.Scalar Operations

In [ ]:
x=torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
#### addition
x+2
##### substraction
x-2

#### multiplication
x*2
#### division
x/2
### int division
(x*100)//3
### mod
((x*100)//3)%2
### power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

2.Element wise operations

In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)

print(a)
print(b)

tensor([[0.6330, 0.5471, 0.6670],
        [0.6537, 0.8150, 0.1835]])
tensor([[0.5036, 0.0750, 0.8362],
        [0.7556, 0.9679, 0.4183]])


In [ ]:
### add
a+b

tensor([[1.1366, 0.6220, 1.5032],
        [1.4093, 1.7829, 0.6018]])

In [ ]:
### substract
a-b

tensor([[ 0.1293,  0.4721, -0.1692],
        [-0.1019, -0.1528, -0.2348]])

In [ ]:
### multiplication
a*b

tensor([[0.3188, 0.0410, 0.5578],
        [0.4939, 0.7888, 0.0768]])

In [ ]:
#### division
a/b

tensor([[1.2567, 7.2981, 0.7977],
        [0.8651, 0.8421, 0.4387]])

In [ ]:
### mod
a%b

tensor([[0.1293, 0.0223, 0.6670],
        [0.6537, 0.8150, 0.1835]])

In [ ]:
#### power
a**b

tensor([[0.7943, 0.9558, 0.7128],
        [0.7253, 0.8204, 0.4920]])

3. single tensor operation

In [ ]:
c=torch.tensor([1,-2,3,-4])

In [ ]:
### abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
### negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d=torch.tensor([1.9,2.3,3.7,4.4])
print(d)

tensor([1.9000, 2.3000, 3.7000, 4.4000])


In [ ]:
### round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
### ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
### floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
### clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

4.Reduction Operations

In [ ]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[4., 6., 5.],
        [1., 9., 2.]])

In [ ]:
## sum
torch.sum(e)

tensor(26)

In [ ]:
### sum along col
torch.sum(e,dim=0)

tensor([ 4,  7, 15])

In [ ]:
### sum along rows
torch.sum(e,dim=1)

tensor([10, 16])

In [ ]:
### mean
torch.mean(e)

tensor(4.5000)

In [ ]:
### mean along col
torch.mean(e,dim=0)

tensor([2.5000, 7.5000, 3.5000])

In [ ]:
## median

torch.median(e)

tensor(4.)

In [ ]:
### max and min
print(torch.max(e))
print(torch.min(e))

tensor(9.)
tensor(1.)


In [ ]:
#### product
torch.prod(e)

tensor(2160.)

In [ ]:
#### standard deviation
torch.std(e)

tensor(2.8810)

In [ ]:
#### variance
torch.var(e)

tensor(8.3000)

In [ ]:
## argmax
torch.argmax(e)

tensor(4)

In [ ]:
## argmin
torch.argmin(e)

tensor(3)

5.Matrix Operations

In [ ]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[6, 2, 2],
        [9, 6, 0]])
tensor([[9, 2],
        [8, 6],
        [1, 8]])


In [ ]:
### matrix multiplication
torch.matmul(f,g)

tensor([[ 72,  40],
        [129,  54]])

In [ ]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

# dot product
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
# transpose

torch.transpose(f,0,1)

tensor([[6, 9],
        [2, 6],
        [2, 0]])

In [ ]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)

h

tensor([[7., 9., 7.],
        [3., 7., 6.],
        [2., 3., 8.]])

In [ ]:
# determinant
torch.det(h)

tensor(123.0000)

In [ ]:
# inverse
torch.inverse(h)

tensor([[ 0.3089, -0.4146,  0.0407],
        [-0.0976,  0.3415, -0.1707],
        [-0.0407, -0.0244,  0.1789]])

5.Comparision Operations

In [ ]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[4, 4, 3],
        [9, 1, 3]])
tensor([[7, 7, 8],
        [6, 4, 8]])


In [ ]:
## greater than
i>j

tensor([[False, False, False],
        [ True, False, False]])

In [ ]:
## less than
i<j

tensor([[ True,  True,  True],
        [False,  True,  True]])

In [ ]:
##equal to
i==j

tensor([[False, False, False],
        [False, False, False]])

In [ ]:
## not equal to
i!=j

tensor([[True, True, True],
        [True, True, True]])

7.Special functions

In [ ]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[3., 3., 8.],
        [1., 0., 1.]])

In [ ]:
# log
torch.log(k)

tensor([[1.6094, 2.1972,   -inf],
        [  -inf, 0.0000, 1.7918]])

In [ ]:
# exp
torch.exp(k)

tensor([[1.4841e+02, 8.1031e+03, 1.0000e+00],
        [1.0000e+00, 2.7183e+00, 4.0343e+02]])

In [ ]:
## sqrt
torch.sqrt(k)

tensor([[2.2361, 3.0000, 0.0000],
        [0.0000, 1.0000, 2.4495]])

In [ ]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.9999, 0.5000],
        [0.5000, 0.7311, 0.9975]])

In [ ]:
# softmax
torch.softmax(k,dim=0)

tensor([[8.8080e-01, 9.5257e-01, 9.9909e-01],
        [1.1920e-01, 4.7426e-02, 9.1105e-04]])

In [ ]:
# relu
torch.relu(k)

tensor([[3., 3., 8.],
        [1., 0., 1.]])

Inplace Operations

In [ ]:
m=torch.rand(size=(2,3))
n=torch.rand(size=(2,3))
print(m)
print(n)

tensor([[0.9160, 0.6158, 0.6043],
        [0.8863, 0.0010, 0.5433]])
tensor([[0.7507, 0.5407, 0.5996],
        [0.1311, 0.8364, 0.7774]])


In [ ]:
m.add_(n)

tensor([[1.6666, 1.1565, 1.2040],
        [1.0174, 0.8373, 1.3207]])

In [ ]:
m.relu_()

tensor([[1.6666, 1.1565, 1.2040],
        [1.0174, 0.8373, 1.3207]])

Copying a Tensor

In [ ]:
a=torch.rand(size=(2,3))
a

tensor([[0.2739, 0.5862, 0.1367],
        [0.3322, 0.8763, 0.9788]])

In [ ]:
b=a
b

tensor([[0.2739, 0.5862, 0.1367],
        [0.3322, 0.8763, 0.9788]])

In [ ]:
b=a.clone()
b

tensor([[0.2739, 0.5862, 0.1367],
        [0.3322, 0.8763, 0.9788]])

Tensor Operation on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device=torch.device('cuda')
print(device)

cuda


In [ ]:
## creating new tensor in GPU
torch.rand(size=(2,3),device=device)

tensor([[0.4871, 0.9135, 0.4166],
        [0.0557, 0.3698, 0.6694]], device='cuda:0')

In [ ]:
## moving an existing tensor to GPU
a=torch.rand(2,3)
a

tensor([[0.9228, 0.5795, 0.9330],
        [0.6912, 0.5552, 0.5343]])

In [ ]:
b=a.to(device=device)

In [ ]:
b+5

tensor([[5.9228, 5.5795, 5.9330],
        [5.6912, 5.5552, 5.5343]], device='cuda:0')

In [ ]:
import torch
import time
size=10000
matrix_cpu1=torch.rand(size,size)
matrix_cpu2=torch.rand(size,size)

matrix_gpu1=matrix_cpu1.to(device)
matrix_gpu2=matrix_cpu2.to(device)

## measure time in cpu
start=time.time()
result=torch.matmul(matrix_cpu1,matrix_cpu2)
end=time.time()
cpu_time=end-start
print("cpu time",end-start)

matrix_gpu1=matrix_cpu1.to(device)
matrix_gpu2=matrix_cpu2.to(device)

## measure time in gpu
start=time.time()
result=torch.matmul(matrix_gpu1,matrix_gpu2)
end=time.time()
gpu_time=end-start
print("gpu time",end-start)

### compare result
print("speedup cpu/gpu time: ",cpu_time/gpu_time)

cpu time 27.982536792755127
gpu time 0.13169002532958984
speedup cpu/gpu time:  212.4878989332812


Reshaping Tensors

In [ ]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b=torch.rand(2,3,4)
b

tensor([[[0.1461, 0.1598, 0.8279, 0.8661],
         [0.3213, 0.2867, 0.0799, 0.5710],
         [0.1567, 0.0575, 0.5600, 0.0076]],

        [[0.6604, 0.6036, 0.3246, 0.1167],
         [0.4808, 0.0597, 0.1441, 0.2576],
         [0.7107, 0.9875, 0.4705, 0.3177]]])

In [ ]:
#permute
b.permute(2,0,1)

tensor([[[0.1461, 0.3213, 0.1567],
         [0.6604, 0.4808, 0.7107]],

        [[0.1598, 0.2867, 0.0575],
         [0.6036, 0.0597, 0.9875]],

        [[0.8279, 0.0799, 0.5600],
         [0.3246, 0.1441, 0.4705]],

        [[0.8661, 0.5710, 0.0076],
         [0.1167, 0.2576, 0.3177]]])

In [ ]:
### unsqueeze
### image

c=torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
## squeeze

a=torch.rand(1,20)
a.squeeze(0).shape

torch.Size([20])

Numpy and pytorch

In [ ]:
import numpy as np

In [ ]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b=a.numpy()

In [ ]:
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])